# Generated by Django 5.2.6 on 2025-09-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='sex',
            field=models.CharField(choices=[('М', 'male'), ('Ж', 'female'), ('-', 'defailt')], default='-', max_length=1),
        ),
    ]
