# Generated by Django 5.2.6 on 2025-10-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_info_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_info',
            name='user',
        ),
    ]
