# Generated by Django 5.2.6 on 2025-10-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_info_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_info',
        ),
    ]
