# Generated by Django 5.2.6 on 2025-10-01 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_delete_profile_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('М', 'male'), ('Ж', 'female'), ('-', 'defailt')], default='-', max_length=1)),
                ('birthd', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='imgs/profile_photos')),
                ('preview', models.TextField(blank=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['birthd'],
            },
        ),
    ]
