# Generated by Django 5.2.6 on 2025-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='photo',
            field=models.ImageField(blank=True, upload_to='C:\\pch_projects\\to_do_project\\todo_project\\madia/'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='sex',
            field=models.CharField(choices=[('М', 'male'), ('Ж', 'female'), ('-', 'default')], default='-', max_length=1),
        ),
    ]
