# Generated by Django 5.2.6 on 2025-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_info_photo_alter_user_info_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='photo',
            field=models.ImageField(blank=True, default='imgs/user_placeholder.png', upload_to='C:\\pch_projects\\to_do_project\\todo_project\\madia/'),
        ),
    ]
