# Generated by Django 5.2.6 on 2025-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_info_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='photo',
            field=models.ImageField(blank=True, upload_to='C:\\pch_projects\\to_do_project\\todo_project\\madia/'),
        ),
    ]
