# Generated by Django 5.2.6 on 2025-10-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_userproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='friends',
            field=models.ManyToManyField(to='account.user_info'),
        ),
    ]
