# Generated by Django 5.2.6 on 2025-10-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_user_info_friends'),
        ('friends', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
        model_name='user_info',
        name='friends',
        ),
        migrations.AddField(
            model_name='user_info',
            name='friends',
            field=models.ManyToManyField(through='friends.Friendship', to='account.user_info'),
        ),
    ]
