# Generated by Django 5.2.6 on 2025-10-16 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_user_info_user_id'),
        ('friends', '0004_remove_friendship_unique_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_id',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('М', 'Male'), ('Ж', 'Female'), ('-', 'Default')], default='-', max_length=1)),
                ('birthd', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('preview', models.TextField(blank=True)),
                ('friends', models.ManyToManyField(through='friends.Friendship', to='account.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['birthd'],
            },
        ),
    ]
