# Generated by Django 5.2.6 on 2025-10-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_user_info_friends_remove_user_info_user_id_and_more'),
        ('friends', '0005_alter_friendship_friend_1_alter_friendship_friend_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
