# Generated by Django 5.2.6 on 2025-10-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
