# Generated by Django 5.2.6 on 2025-10-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='todo_images/report')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='todos.todo')),
            ],
        ),
    ]
