# Generated by Django 5.2.6 on 2025-10-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todoreport_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoreport',
            name='todo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todos.todo'),
        ),
    ]
