# Generated by Django 5.2.6 on 2025-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_alter_todoreport_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='active',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('no_report', 'No Report'), ('no_confirm', 'No Confirm'), ('confirmed', 'Confirmed')], default='no_report'),
        ),
    ]
