# Generated by Django 5.2.6 on 2025-10-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_remove_todo_active_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
