# Generated by Django 5.2.6 on 2025-10-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_rename_user_id_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=560),
        ),
    ]
