# Generated by Django 5.2.6 on 2025-10-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friend',
        ),
    ]
