# Generated by Django 5.2.6 on 2025-10-13 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_alter_user_info_friends'),
        ('friends', '0002_delete_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='account.user_info')),
                ('friend_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='account.user_info')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('friend_1', 'friend_2'), name='unique_friends')],
            },
        ),
    ]
