# Generated by Django 5.2.6 on 2025-10-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friends',
        ),
    ]
