# Generated by Django 5.2.6 on 2025-10-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_user_info_friends_remove_user_info_user_id_and_more'),
        ('friends', '0004_remove_friendship_unique_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friend_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='account.profile'),
        ),
    ]
